// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'web-api-key',
    appId: 'web-app-id',
    messagingSenderId: 'web-sender-id',
    projectId: 'web-project-id',
    authDomain: 'web-auth-domain',
    storageBucket: 'web-storage-bucket',
    measurementId: 'web-measurement-id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'android-api-key',
    appId: 'android-app-id',
    messagingSenderId: 'android-sender-id',
    projectId: 'android-project-id',
    storageBucket: 'android-storage-bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'ios-api-key',
    appId: 'ios-app-id',
    messagingSenderId: 'ios-sender-id',
    projectId: 'ios-project-id',
    storageBucket: 'ios-storage-bucket',
    iosBundleId: 'ios-bundle-id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'macOS-api-key',
    appId: 'macOS-app-id',
    messagingSenderId: 'macOS-sender-id',
    projectId: 'macOS-project-id',
    storageBucket: 'macOS-storage-bucket',
    iosBundleId: 'macOS-bundle-id',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'windows-api-key',
    appId: 'windows-app-id',
    messagingSenderId: 'windows-sender-id',
    projectId: 'windows-project-id',
    authDomain: 'windows-auth-domain',
    storageBucket: 'windows-storage-bucket',
    measurementId: 'windows-measurement-id',
  );
}
