// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ99O1ij2Y4vXOurEfFSv97KuZt1QBm0c',
    appId: '1:530687307816:web:340c07920d80c4487f051d',
    messagingSenderId: '530687307816',
    projectId: 'login-bloc-4df39',
    authDomain: 'login-bloc-4df39.firebaseapp.com',
    storageBucket: 'login-bloc-4df39.firebasestorage.app',
    measurementId: 'G-B1FF7T7YN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPU2NXz0eDfQbopygcYrkm0Bs_Cvc2PqI',
    appId: '1:530687307816:android:c61c085ffd110ee57f051d',
    messagingSenderId: '530687307816',
    projectId: 'login-bloc-4df39',
    storageBucket: 'login-bloc-4df39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhR5Sdy8o8mKCxa0pdaEM9a4MMv62N3wM',
    appId: '1:530687307816:ios:04043fdde10ee20d7f051d',
    messagingSenderId: '530687307816',
    projectId: 'login-bloc-4df39',
    storageBucket: 'login-bloc-4df39.firebasestorage.app',
    iosBundleId: 'com.example.loginBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhR5Sdy8o8mKCxa0pdaEM9a4MMv62N3wM',
    appId: '1:530687307816:ios:04043fdde10ee20d7f051d',
    messagingSenderId: '530687307816',
    projectId: 'login-bloc-4df39',
    storageBucket: 'login-bloc-4df39.firebasestorage.app',
    iosBundleId: 'com.example.loginBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ99O1ij2Y4vXOurEfFSv97KuZt1QBm0c',
    appId: '1:530687307816:web:c8d3b9c067949c977f051d',
    messagingSenderId: '530687307816',
    projectId: 'login-bloc-4df39',
    authDomain: 'login-bloc-4df39.firebaseapp.com',
    storageBucket: 'login-bloc-4df39.firebasestorage.app',
    measurementId: 'G-T0Z81NPKW1',
  );
}
